import { BASE_SYSTEM_URL } from 'Contants/Common.js'

export const USER_LOGIN_REQUEST =  BASE_SYSTEM_URL + '/USER_LOGIN_REQUEST'

export const USER_LOGIN_SUCCESS =  BASE_SYSTEM_URL + '/USER_LOGIN_SUCCESS'

export const USER_LOGIN_FAILURE =  BASE_SYSTEM_URL + '/USER_LOGIN_FAILURE'